[package]
name = "sync-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
sync-protocol = { path = "../sync-protocol" }
tokio.workspace = true
tokio-tungstenite.workspace = true

[[bin]]
name = "spike-relay"
path = "src/main.rs"
