[package]
name = "platform-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
domain = { path = "../domain" }
graph-archive = { path = "../graph-archive" }
graph-core = { path = "../graph-core" }
query = { path = "../query" }
sync-protocol = { path = "../sync-protocol" }
serde_json.workspace = true
wasm-bindgen.workspace = true
