[package]
name = "query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
domain = { path = "../domain" }
hex.workspace = true
oxigraph.workspace = true
roaring.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
spargebra.workspace = true
thiserror.workspace = true
