import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parse, TYPE } from "@formatjs/icu-messageformat-parser";

const root = resolve(import.meta.dirname, "..");
const localeDir = resolve(root, "apps/client/src/i18n/locales");
const output = resolve(root, "apps/client/src/i18n/generated/messages.ts");
const localeDefinitions = JSON.parse(
  await readFile(resolve(localeDir, "manifest.json"), "utf8"),
);

if (!Array.isArray(localeDefinitions) || localeDefinitions.length === 0) {
  throw new Error("locale manifest must contain at least one locale");
}
const localeFiles = localeDefinitions.map(({ tag }) => tag);
if (localeFiles[0] !== "en" || new Set(localeFiles).size !== localeFiles.length) {
  throw new Error("locale manifest must start with en and contain unique tags");
}
for (const definition of localeDefinitions) {
  if (
    typeof definition.tag !== "string" ||
    !/^[a-z]{2,3}(?:-[A-Z]{2})?$/.test(definition.tag) ||
    !["ltr", "rtl"].includes(definition.direction) ||
    typeof definition.labelKey !== "string"
  ) {
    throw new Error(`invalid locale definition: ${JSON.stringify(definition)}`);
  }
}

const catalogs = Object.fromEntries(
  await Promise.all(
    localeFiles.map(async (locale) => [
      locale,
      JSON.parse(await readFile(resolve(localeDir, `${locale}.json`), "utf8")),
    ]),
  ),
);

const baseKeys = Object.keys(catalogs.en).sort();
for (const definition of localeDefinitions) {
  if (!baseKeys.includes(definition.labelKey)) {
    throw new Error(`${definition.tag} label key is missing: ${definition.labelKey}`);
  }
}
for (const locale of localeFiles) {
  const keys = Object.keys(catalogs[locale]).sort();
  const missing = baseKeys.filter((key) => !keys.includes(key));
  const extra = keys.filter((key) => !baseKeys.includes(key));
  if (missing.length || extra.length) {
    throw new Error(
      `${locale} catalog mismatch\nmissing: ${missing.join(", ")}\nextra: ${extra.join(", ")}`,
    );
  }
}

function mergeType(previous, next) {
  if (!previous || previous === next) return next;
  return [...new Set([...previous.split(" | "), ...next.split(" | ")])].sort().join(" | ");
}

function collectArguments(elements, argumentsByName) {
  for (const element of elements) {
    switch (element.type) {
      case TYPE.argument:
        argumentsByName.set(element.value, mergeType(argumentsByName.get(element.value), "string | number"));
        break;
      case TYPE.number:
      case TYPE.plural:
        argumentsByName.set(element.value, mergeType(argumentsByName.get(element.value), "number"));
        break;
      case TYPE.date:
      case TYPE.time:
        argumentsByName.set(element.value, mergeType(argumentsByName.get(element.value), "Date | number"));
        break;
      case TYPE.select:
        argumentsByName.set(element.value, mergeType(argumentsByName.get(element.value), "string"));
        break;
      default:
        break;
    }
    if ("options" in element) {
      for (const option of Object.values(element.options)) {
        collectArguments(option.value, argumentsByName);
      }
    }
    if ("children" in element) collectArguments(element.children, argumentsByName);
  }
}

const argumentMaps = new Map();
for (const key of baseKeys) {
  const baseArguments = new Map();
  for (const locale of localeFiles) {
    const argumentsForLocale = new Map();
    collectArguments(parse(catalogs[locale][key]), argumentsForLocale);
    if (locale === "en") {
      for (const entry of argumentsForLocale) baseArguments.set(...entry);
      continue;
    }
    const baseShape = JSON.stringify([...baseArguments.entries()].sort());
    const localeShape = JSON.stringify([...argumentsForLocale.entries()].sort());
    if (baseShape !== localeShape) {
      throw new Error(`${locale}:${key} arguments differ from en`);
    }
  }
  argumentMaps.set(key, baseArguments);
}

const lines = [
  "// Generated by scripts/generate-i18n.mjs. Do not edit by hand.",
  "",
  `export const LOCALE_DEFINITIONS = ${JSON.stringify(localeDefinitions, null, 2)} as const;`,
  "export type SupportedLocale = (typeof LOCALE_DEFINITIONS)[number][\"tag\"];",
  "export type TextDirection = (typeof LOCALE_DEFINITIONS)[number][\"direction\"];",
  "export const SUPPORTED_LOCALES = LOCALE_DEFINITIONS.map(({ tag }) => tag);",
  "",
  "export interface MessageArgumentMap {",
];
for (const key of baseKeys) {
  const args = argumentMaps.get(key);
  if (args.size === 0) {
    lines.push(`  ${JSON.stringify(key)}: undefined;`);
    continue;
  }
  const fields = [...args.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, type]) => `readonly ${JSON.stringify(name)}: ${type}`)
    .join("; ");
  lines.push(`  ${JSON.stringify(key)}: { ${fields} };`);
}
lines.push(
  "}",
  "",
  "export type MessageKey = keyof MessageArgumentMap;",
  "export type MessageFunction = <K extends MessageKey>(",
  "  key: K,",
  "  ...args: MessageArgumentMap[K] extends undefined",
  "    ? []",
  "    : [values: MessageArgumentMap[K]]",
  ") => string;",
  "",
);

const generated = `${lines.join("\n")}\n`;
if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error("generated i18n types are stale; run pnpm i18n:generate");
  }
} else {
  await mkdir(resolve(output, ".."), { recursive: true });
  await writeFile(output, generated);
}
